[package]
name = "secret-vault"
version = "0.1.0"
authors = ["Abdulla Abdurakhmanov <me@abdolence.dev>"]
edition = "2021"
license = "Apache-2.0"
description = "Library provides a secure vault to store application secrets in memory coming from Google/AWS/other secret managers"
homepage = "https://github.com/abdolence/secret-vault-rs"
repository = "https://github.com/abdolence/secret-vault-rs"
documentation = "https://docs.rs/secret-vault"
keywords = ["secret", "google", "aws"]
readme = "../README.md"
include = ["Cargo.toml", "src/**/*.rs", "../README.md", "../LICENSE", "../SECURITY.md"]

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "secret_vault"
path = "src/lib.rs"
bench = false

[dependencies]
tracing = "0.1"
secret-vault-value = { version = "0.1" }
rvstruct = "0.3"
rsb_derive = "0.5"
async-trait = "0.1"
chrono = { version = "0.4" }
zeroize = { version = "1.5", features = ["std", "derive"] }
ring = { version = "0.16", features = ["default", "std"], optional = true }
region = { version = "3.0.0", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
gcloud-sdk = { version = "0.15", optional = true, features = ["google-cloud-secretmanager-v1"] }
tonic = { version = "0.7", optional = true }
aws-config = { version = "0.15", optional = true }
aws-sdk-secretsmanager = { version = "0.15", optional = true }

[dev-dependencies]
cargo-husky = { version = "1.5", default-features = false, features = ["run-for-all", "prepush-hook", "run-cargo-fmt"] }
serde_json = { version = "1" }
proptest = "1.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
criterion = { version = "0.3", features = ["html_reports", "futures", "tokio", "async_tokio"] }

[features]
default = []
serde = ["dep:serde", "chrono/serde", "secret-vault-value/serde"]
encrypted-ring = ["dep:ring"]
gcloud = ["dep:gcloud-sdk", "dep:tonic"]
gcloud-secretmanager = ["gcloud"]
aws = ["dep:aws-config", "dep:aws-sdk-secretsmanager"]
aws-secretmanager = ["aws"]

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "gcloud_secret_manager_vault"
path = "examples/gcloud_secret_manager_vault.rs"
required-features = ["gcloud-secretmanager", "encrypted-ring"]

[[example]]
name = "aws_secret_manager_vault"
path = "examples/aws_secret_manager_vault.rs"
required-features = ["aws-secretmanager", "encrypted-ring"]

[[example]]
name = "insecure_env_secret_vault"
path = "examples/insecure_env_secret_vault.rs"

[[bench]]
name = "ring_encrypted_vault"
path = "benches/ring_encrypted_vault.rs"
harness = false

[[bench]]
name = "read_vault_bench"
path = "benches/read_vault_bench.rs"
harness = false
