[package]
name = "secret-vault"
version = "0.1.0"
authors = ["Abdulla Abdurakhmanov <me@abdolence.dev>"]
edition = "2021"
license = "Apache-2.0"
description = "Library provides a simple implementation of a secure vault to store application secrets in memory"
homepage = "https://github.com/abdolence/secret-vault-rs"
repository = "https://github.com/abdolence/secret-vault-rs"
documentation = "https://docs.rs/secret-vault"
keywords = ["secret", "google", "client"]
categories = ["security"]
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "../README.md", "../LICENSE", "../SECURITY.md"]

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "secret_vault"
path = "src/lib.rs"

[dependencies]
tracing = "0.1"
secret-vault-value = { version = "0.1", path = "../secret-value" }
rvstruct = "0.3"
rsb_derive = "0.5"
async-trait = "0.1"
zeroize = { version = "1.5", features = ["std", "derive"] }
ring = { version = "0.16", features = ["default", "std"], optional = true }
region = { version = "3.0.0", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
gcloud-sdk = { version = "0.14", optional = true, features = ["google-cloud-secretmanager-v1"], path = "../../gcloud-sdk/gcloud-sdk" }
tonic = { version = "0.7", optional = true }

[dev-dependencies]
cargo-husky = { version = "1.5", default-features = false, features = ["run-for-all", "prepush-hook", "run-cargo-fmt"] }
serde_json = { version = "1" }
proptest = "1.0"
tracing-subscriber = { version ="0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
criterion = { version="0.3", features=["html_reports"] }

[features]
default = []
serde = ["dep:serde"]
memory-protect = ["dep:region"]
encrypted-ring = ["dep:ring"]
gcloud = ["dep:gcloud-sdk", "dep:tonic"]
gcloud-secretmanager = ["gcloud"]

[package.metadata.docs.rs]
all-features = true

[[example]]
name="gcloud_secret_manager_vault"
required-features = ["gcloud-secretmanager", "encrypted-ring", "memory-protect"]

[[bench]]
name = "ring_encrypted_vault"
harness = false
